name: Self-hosted runner (AMD mi250 scheduled CI caller)

on:
  workflow_run:
    workflows: ["Self-hosted runner (AMD scheduled CI caller)"]
    branches: ["main"]
    types: [completed]
  push:
    branches:
      - test-arc-runner-transformers*

jobs:
  example-ci:
    name: Example CI
    uses: jitesh-gupta/hf-workflows/.github/workflows/transformers_amd_ci_scheduled_arc_scale_set.yaml@test-arc-runner
    with:
      job: run_examples_gpu
      slack_report_channel: "#amd-hf-ci"
      runner_scale_set: test-linux-mi300
      docker: huggingface/transformers-pytorch-amd-gpu
      ci_event: Scheduled CI (AMD) - mi250
    secrets: inherit
